name: Deploy to VPS

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy with SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/myapp
          git pull origin master
          source venv/bin/activate
          pip install -r requirements.txt
          pkill uvicorn || true
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 > log.txt 2>&1 &
